<a href="https://colab.research.google.com/github/Bala-452/LGMVIP-Web/blob/main/regg_restaurant_revenue_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('train.csv.zip')
xtest=pd.read_csv('test.csv.zip')

In [ ]:
df.drop(columns=['Id'])

,Open Date,City,City Group,Type,P1,P2,P3,P4,P5,P6,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
0,07/17/1999,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,2,...,3.0,5,3,4,5,5,4,3,4,5653753.0
1,02/14/2008,Ankara,Big Cities,FC,4,5.0,4.0,4.0,1,2,...,3.0,0,0,0,0,0,0,0,0,6923131.0
2,03/09/2013,Diyarbakır,Other,IL,2,4.0,2.0,5.0,2,3,...,3.0,0,0,0,0,0,0,0,0,2055379.0
3,02/02/2012,Tokat,Other,IL,6,4.5,6.0,6.0,4,4,...,7.5,25,12,10,6,18,12,12,6,2675511.0
4,05/09/2009,Gaziantep,Other,IL,3,4.0,3.0,4.0,2,2,...,3.0,5,1,3,2,3,4,3,3,4316715.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,06/25/2008,Trabzon,Other,FC,2,3.0,3.0,5.0,4,2,...,3.0,0,0,0,0,0,0,0,0,5787594.0
133,10/12/2006,İzmir,Big Cities,FC,4,5.0,4.0,4.0,2,3,...,3.0,0,0,0,0,0,0,0,0,9262754.0
134,07/08/2006,Kayseri,Other,FC,3,4.0,4.0,4.0,2,3,...,3.0,0,0,0,0,0,0,0,0,2544857.0
135,10/29/2010,İstanbul,Big Cities,FC,4,5.0,4.0,5.0,2,2,...,3.0,0,0,0,0,0,0,0,0,7217634.0
136,09/01/2009,İstanbul,Big Cities,FC,4,5.0,3.0,5.0,2,2,...,3.0,0,0,0,0,0,0,0,0,6363241.0

In [ ]:
df.columns

Index(['Id', 'Open Date', 'City', 'City Group', 'Type', 'P1', 'P2', 'P3', 'P4',
       'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15',
       'P16', 'P17', 'P18', 'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25',
       'P26', 'P27', 'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35',
       'P36', 'P37', 'revenue'],
      dtype='object')

In [ ]:
df.describe()

,Id,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,revenue
count,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,...,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,1.370000e+02
mean,68.000000,4.014599,4.408759,4.317518,4.372263,2.007299,3.357664,5.423358,5.153285,5.445255,...,3.135036,2.729927,1.941606,2.525547,1.138686,2.489051,2.029197,2.211679,1.116788,4.453533e+06
std,39.692569,2.910391,1.514900,1.032337,1.016462,1.209620,2.134235,2.296809,1.858567,1.834793,...,1.680887,5.536647,3.512093,5.230117,1.698540,5.165093,3.436272,4.168211,1.790768,2.576072e+06
min,0.000000,1.000000,1.000000,0.000000,3.000000,1.000000,1.000000,1.000000,1.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.149870e+06
25%,34.000000,2.000000,4.000000,4.000000,4.000000,1.000000,2.000000,5.000000,4.000000,4.000000,...,2.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.999068e+06
50%,68.000000,3.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,5.000000,5.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.939804e+06
75%,102.000000,4.000000,5.000000,5.000000,5.000000,2.000000,4.000000,5.000000,5.000000,5.000000,...,3.000000,4.000000,3.000000,3.000000,2.000000,3.000000,4.000000,3.000000,2.000000,5.166635e+06
max,136.000000,12.000000,7.500000,7.500000,7.500000,8.000000,10.000000,10.000000,10.000000,10.000000,...,7.500000,25.000000,15.000000,25.000000,6.000000,24.000000,15.000000,20.000000,8.000000,1.969694e+07

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
l=[i for i in df.columns if df[i].dtype=='object']
for i in l:
  df[i]= label_encoder.fit_transform(df[i])

In [ ]:
a=[i for i in xtest.columns if xtest[i].dtype=="object"]
for i in a:
  xtest[i]=label_encoder.fit_transform(xtest[i])

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
y

0      5653753.0
1      6923131.0
2      2055379.0
3      2675511.0
4      4316715.0
         ...
132    5787594.0
133    9262754.0
134    2544857.0
135    7217634.0
136    6363241.0
Name: revenue, Length: 137, dtype: float64

In [ ]:
x.shape

(137, 42)

In [ ]:
y.shape

(137,)

In [ ]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
xtest=st.fit_transform(xtest)
xtest

array([[-1.73203349, -1.59301097,  0.20983168, ..., -0.56765883,
        -0.5173456 , -0.58041125],
       [-1.73199885, -1.12184544, -0.31202557, ..., -0.56765883,
        -0.5173456 , -0.58041125],
       [-1.73196421,  1.04327231, -1.4506232 , ..., -0.56765883,
        -0.5173456 , -0.58041125],
       ...,
       [ 1.73196421,  1.70514769,  0.96889678, ...,  0.67120965,
         0.53369453,  0.61201043],
       [ 1.73199885,  0.85256246,  0.96889678, ..., -0.56765883,
        -0.5173456 , -0.58041125],
       [ 1.73203349,  0.77403487,  0.96889678, ...,  0.67120965,
         0.00817446, -0.58041125]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.71945391, -0.15950748,  0.88075847, ...,  0.57563408,
         0.18982104,  1.61595083],
       [-1.69416782, -1.25723944, -1.49685552, ..., -0.59268991,
        -0.53255348, -0.62592526],
       [-1.66888173, -1.15512483, -0.90245203, ..., -0.59268991,
        -0.53255348, -0.62592526],
       ...,
       [ 1.66888173, -0.26162208, -0.22313374, ..., -0.59268991,
        -0.53255348, -0.62592526],
       [ 1.69416782,  0.96375313,  0.88075847, ..., -0.59268991,
        -0.53255348, -0.62592526],
       [ 1.71945391,  0.35106552,  0.88075847, ..., -0.59268991,
        -0.53255348, -0.62592526]])

In [ ]:
# from sklearn.preprocessing import StandardScaler
sy=StandardScaler()
y=pd.DataFrame(y)
y=sy.fit_transform(y)
y

array([[ 4.67620885e-01],
       [ 9.62186442e-01],
       [-9.34350664e-01],
       [-6.92739475e-01],
       [-5.33058546e-02],
       [ 2.19658233e-01],
       [ 2.77833615e-01],
       [ 1.48342577e-02],
       [ 1.94402770e-01],
       [ 3.85986933e-01],
       [-2.76000577e-01],
       [ 2.75782306e-01],
       [-1.05931693e+00],
       [ 1.38005969e-01],
       [-9.56278836e-01],
       [-4.81021306e-01],
       [ 5.93902192e+00],
       [ 1.46493971e+00],
       [ 3.44414888e-01],
       [-9.47381255e-01],
       [ 4.17743470e-01],
       [-1.28714830e+00],
       [-1.93811427e-01],
       [-5.66677618e-01],
       [ 1.73399053e+00],
       [-2.62954012e-01],
       [-8.51734889e-01],
       [ 3.82499512e-01],
       [ 9.83430252e-02],
       [-3.91810949e-01],
       [-5.63120066e-01],
       [-9.33078579e-01],
       [-4.64265630e-01],
       [-8.11302070e-01],
       [-1.37395534e-01],
       [-2.14149979e-01],
       [-5.55301322e-01],
       [-6.67346090e-01],
       [ 3.92794633e-01],
       [-2.47590032e-01],
       [ 9.28427297e-01],
       [ 3.92356896e-02],
       [ 1.94308484e-01],
       [-6.70479354e-01],
       [-7.37757066e-02],
       [-2.72981080e-01],
       [-7.90035273e-02],
       [ 1.32931715e+00],
       [ 1.07075314e+00],
       [ 1.62746968e+00],
       [-8.95109281e-01],
       [-4.59934308e-01],
       [-1.04817518e+00],
       [ 4.44834008e-01],
       [ 7.72731700e-02],
       [ 9.69215831e-01],
       [-8.03770081e-01],
       [-4.65468364e-01],
       [-5.64588905e-01],
       [-3.32365040e-01],
       [-5.02039343e-01],
       [-4.01143540e-02],
       [ 3.24422311e-01],
       [-1.10410328e+00],
       [-7.41152337e-01],
       [-1.05096559e+00],
       [-1.00185025e+00],
       [-1.56156546e-01],
       [-2.40317525e-01],
       [-3.90060810e-01],
       [-1.83416175e-01],
       [-1.23549095e-01],
       [-7.51234340e-01],
       [-4.30820123e-01],
       [ 4.08035495e-01],
       [ 4.71257042e+00],
       [ 5.33342081e-02],
       [-9.93001764e-01],
       [-2.26827971e-01],
       [ 7.24557872e-01],
       [-2.82924381e-01],
       [-1.50746776e-01],
       [-2.51703951e-01],
       [ 5.89351420e-01],
       [-7.90833979e-02],
       [ 1.18502961e+00],
       [-4.29411284e-01],
       [ 5.66131683e-01],
       [-9.46070988e-01],
       [-8.13921825e-01],
       [-4.00273723e-01],
       [-9.23415020e-01],
       [ 9.07365624e-01],
       [-4.06231288e-01],
       [-2.72655753e-01],
       [-1.24014974e+00],
       [ 7.63286136e-01],
       [ 8.73224658e-01],
       [-8.21631867e-01],
       [ 3.55392514e+00],
       [ 2.02552432e+00],
       [ 1.18809760e-01],
       [-6.68372719e-01],
       [-9.35873153e-03],
       [ 5.53070040e-03],
       [-6.47341825e-01],
       [ 1.69575492e-01],
       [-4.69433451e-01],
       [-3.44082637e-01],
       [-9.12743735e-02],
       [-5.84203168e-01],
       [-5.69014904e-01],
       [-2.60768675e-01],
       [-9.18126030e-01],
       [-1.16142561e-01],
       [ 1.67320025e-01],
       [ 1.73029466e+00],
       [-9.48608145e-01],
       [-1.01521591e+00],
       [-2.62409334e-01],
       [-1.50377423e-01],
       [-3.92907319e-01],
       [-6.50215029e-02],
       [-7.39888246e-02],
       [-2.50725634e-01],
       [ 1.27432275e-01],
       [-1.70565975e-01],
       [ 1.22289215e+00],
       [-8.06378147e-01],
       [-2.00155098e-01],
       [-4.19763699e-01],
       [-4.88540438e-01],
       [ 5.19767014e-01],
       [ 1.87373285e+00],
       [-7.43643909e-01],
       [ 1.07692850e+00],
       [ 7.44046290e-01]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid=train_test_split(x,y,test_size=0.2,random_state=10)

In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam
model=Sequential()
model.add(Dense(units=25,input_dim=42,activation="tanh"))
model.add(Dense(units=30,activation="relu"))
model.add(Dense(units=30,activation="relu"))
model.add(Dense(1))

In [ ]:
model.compile(loss='mse',optimizer=Adam(learning_rate=0.001),metrics=['RootMeanSquaredError'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 25)                1075

 dense_1 (Dense)             (None, 30)                780

 dense_2 (Dense)             (None, 30)                930

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 2,816
Trainable params: 2,816
Non-trainable params: 0
_________________________________________________________________

In [ ]:

model.fit(x_train,y_train,epochs=50,validation_data=(x_valid,y_valid))

Epoch 1/50
4/4 [==============================] - 7s 99ms/step - loss: 0.9631 - root_mean_squared_error: 0.9814 - val_loss: 1.4135 - val_root_mean_squared_error: 1.1889
Epoch 2/50
4/4 [==============================] - 0s 12ms/step - loss: 0.8870 - root_mean_squared_error: 0.9418 - val_loss: 1.4214 - val_root_mean_squared_error: 1.1922
Epoch 3/50
4/4 [==============================] - 0s 12ms/step - loss: 0.8496 - root_mean_squared_error: 0.9218 - val_loss: 1.4009 - val_root_mean_squared_error: 1.1836
Epoch 4/50
4/4 [==============================] - 0s 11ms/step - loss: 0.8169 - root_mean_squared_error: 0.9038 - val_loss: 1.3906 - val_root_mean_squared_error: 1.1793
Epoch 5/50
4/4 [==============================] - 0s 12ms/step - loss: 0.7855 - root_mean_squared_error: 0.8863 - val_loss: 1.3791 - val_root_mean_squared_error: 1.1743
Epoch 6/50
4/4 [==============================] - 0s 13ms/step - loss: 0.7589 - root_mean_squared_error: 0.8711 - val_loss: 1.3622 - val_root_mean_squared_error: 1.1671
Epoch 7/50
4/4 [==============================] - 0s 14ms/step - loss: 0.7405 - root_mean_squared_error: 0.8605 - val_loss: 1.3415 - val_root_mean_squared_error: 1.1582
Epoch 8/50
4/4 [==============================] - 0s 12ms/step - loss: 0.7211 - root_mean_squared_error: 0.8492 - val_loss: 1.3259 - val_root_mean_squared_error: 1.1515
Epoch 9/50
4/4 [==============================] - 0s 12ms/step - loss: 0.7036 - root_mean_squared_error: 0.8388 - val_loss: 1.3160 - val_root_mean_squared_error: 1.1472
Epoch 10/50
4/4 [==============================] - 0s 12ms/step - loss: 0.6885 - root_mean_squared_error: 0.8298 - val_loss: 1.3045 - val_root_mean_squared_error: 1.1422
Epoch 11/50
4/4 [==============================] - 0s 12ms/step - loss: 0.6747 - root_mean_squared_error: 0.8214 - val_loss: 1.2992 - val_root_mean_squared_error: 1.1398
Epoch 12/50
4/4 [==============================] - 0s 12ms/step - loss: 0.6595 - root_mean_squared_error: 0.8121 - val_loss: 1.2959 - val_root_mean_squared_error: 1.1384
Epoch 13/50
4/4 [==============================] - 0s 12ms/step - loss: 0.6436 - root_mean_squared_error: 0.8023 - val_loss: 1.2948 - val_root_mean_squared_error: 1.1379
Epoch 14/50
4/4 [==============================] - 0s 13ms/step - loss: 0.6312 - root_mean_squared_error: 0.7945 - val_loss: 1.2943 - val_root_mean_squared_error: 1.1377
Epoch 15/50
4/4 [==============================] - 0s 12ms/step - loss: 0.6187 - root_mean_squared_error: 0.7866 - val_loss: 1.3011 - val_root_mean_squared_error: 1.1407
Epoch 16/50
4/4 [==============================] - 0s 17ms/step - loss: 0.6040 - root_mean_squared_error: 0.7772 - val_loss: 1.3090 - val_root_mean_squared_error: 1.1441
Epoch 17/50
4/4 [==============================] - 0s 12ms/step - loss: 0.5928 - root_mean_squared_error: 0.7699 - val_loss: 1.3141 - val_root_mean_squared_error: 1.1463
Epoch 18/50
4/4 [==============================] - 0s 15ms/step - loss: 0.5790 - root_mean_squared_error: 0.7609 - val_loss: 1.3118 - val_root_mean_squared_error: 1.1453
Epoch 19/50
4/4 [==============================] - 0s 13ms/step - loss: 0.5628 - root_mean_squared_error: 0.7502 - val_loss: 1.2979 - val_root_mean_squared_error: 1.1393
Epoch 20/50
4/4 [==============================] - 0s 12ms/step - loss: 0.5506 - root_mean_squared_error: 0.7420 - val_loss: 1.2882 - val_root_mean_squared_error: 1.1350
Epoch 21/50
4/4 [==============================] - 0s 12ms/step - loss: 0.5382 - root_mean_squared_error: 0.7336 - val_loss: 1.2868 - val_root_mean_squared_error: 1.1344
Epoch 22/50
4/4 [==============================] - 0s 12ms/step - loss: 0.5279 - root_mean_squared_error: 0.7265 - val_loss: 1.2929 - val_root_mean_squared_error: 1.1371
Epoch 23/50
4/4 [==============================] - 0s 13ms/step - loss: 0.5136 - root_mean_squared_error: 0.7166 - val_loss: 1.2965 - val_root_mean_squared_error: 1.1387
Epoch 24/50
4/4 [==============================] - 0s 12ms/step - loss: 0.5014 - root_mean_squared_error: 0.7081 - val_loss: 1.2970 - val_root_mean_squared_error: 1.1389
Epoch 25/50
4/4 [==============================] - 0s 12ms/step - loss: 0.4878 - root_mean_squared_error: 0.6984 - val_loss: 1.3091 - val_root_mean_squared_error: 1.1442
Epoch 26/50
4/4 [==============================] - 0s 13ms/step - loss: 0.4734 - root_mean_squared_error: 0.6881 - val_loss: 1.3229 - val_root_mean_squared_error: 1.1502
Epoch 27/50
4/4 [==============================] - 0s 12ms/step - loss: 0.4585 - root_mean_squared_error: 0.6772 - val_loss: 1.3388 - val_root_mean_squared_error: 1.1571
Epoch 28/50
4/4 [==============================] - 0s 11ms/step - loss: 0.4456 - root_mean_squared_error: 0.6675 - val_loss: 1.3496 - val_root_mean_squared_error: 1.1617
Epoch 29/50
4/4 [==============================] - 0s 12ms/step - loss: 0.4352 - root_mean_squared_error: 0.6597 - val_loss: 1.3663 - val_root_mean_squared_error: 1.1689
Epoch 30/50
4/4 [==============================] - 0s 12ms/step - loss: 0.4229 - root_mean_squared_error: 0.6503 - val_loss: 1.3807 - val_root_mean_squared_error: 1.1750
Epoch 31/50
4/4 [==============================] - 0s 13ms/step - loss: 0.4109 - root_mean_squared_error: 0.6411 - val_loss: 1.3774 - val_root_mean_squared_error: 1.1736
Epoch 32/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3982 - root_mean_squared_error: 0.6310 - val_loss: 1.3917 - val_root_mean_squared_error: 1.1797
Epoch 33/50
4/4 [==============================] - 0s 13ms/step - loss: 0.3871 - root_mean_squared_error: 0.6221 - val_loss: 1.4099 - val_root_mean_squared_error: 1.1874
Epoch 34/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3780 - root_mean_squared_error: 0.6148 - val_loss: 1.4126 - val_root_mean_squared_error: 1.1885
Epoch 35/50
4/4 [==============================] - 0s 13ms/step - loss: 0.3657 - root_mean_squared_error: 0.6047 - val_loss: 1.4111 - val_root_mean_squared_error: 1.1879
Epoch 36/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3487 - root_mean_squared_error: 0.5905 - val_loss: 1.4156 - val_root_mean_squared_error: 1.1898
Epoch 37/50
4/4 [==============================] - 0s 17ms/step - loss: 0.3402 - root_mean_squared_error: 0.5833 - val_loss: 1.4271 - val_root_mean_squared_error: 1.1946
Epoch 38/50
4/4 [==============================] - 0s 15ms/step - loss: 0.3296 - root_mean_squared_error: 0.5741 - val_loss: 1.4301 - val_root_mean_squared_error: 1.1958
Epoch 39/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3195 - root_mean_squared_error: 0.5653 - val_loss: 1.4355 - val_root_mean_squared_error: 1.1981
Epoch 40/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3070 - root_mean_squared_error: 0.5541 - val_loss: 1.4518 - val_root_mean_squared_error: 1.2049
Epoch 41/50
4/4 [==============================] - 0s 12ms/step - loss: 0.3021 - root_mean_squared_error: 0.5497 - val_loss: 1.4750 - val_root_mean_squared_error: 1.2145
Epoch 42/50
4/4 [==============================] - 0s 12ms/step - loss: 0.2894 - root_mean_squared_error: 0.5380 - val_loss: 1.4646 - val_root_mean_squared_error: 1.2102
Epoch 43/50
4/4 [==============================] - 0s 12ms/step - loss: 0.2818 - root_mean_squared_error: 0.5309 - val_loss: 1.4632 - val_root_mean_squared_error: 1.2096
Epoch 44/50
4/4 [==============================] - 0s 12ms/step - loss: 0.2717 - root_mean_squared_error: 0.5212 - val_loss: 1.4709 - val_root_mean_squared_error: 1.2128
Epoch 45/50
4/4 [==============================] - 0s 12ms/step - loss: 0.2679 - root_mean_squared_error: 0.5176 - val_loss: 1.4911 - val_root_mean_squared_error: 1.2211
Epoch 46/50
4/4 [==============================] - 0s 14ms/step - loss: 0.2578 - root_mean_squared_error: 0.5077 - val_loss: 1.5027 - val_root_mean_squared_error: 1.2258
Epoch 47/50
4/4 [==============================] - 0s 11ms/step - loss: 0.2498 - root_mean_squared_error: 0.4998 - val_loss: 1.5132 - val_root_mean_squared_error: 1.2301
Epoch 48/50
4/4 [==============================] - 0s 13ms/step - loss: 0.2409 - root_mean_squared_error: 0.4908 - val_loss: 1.5143 - val_root_mean_squared_error: 1.2306
Epoch 49/50
4/4 [==============================] - 0s 12ms/step - loss: 0.2305 - root_mean_squared_error: 0.4801 - val_loss: 1.5346 - val_root_mean_squared_error: 1.2388
Epoch 50/50
4/4 [==============================] - 0s 12ms/step - loss: 0.2234 - root_mean_squared_error: 0.4727 - val_loss: 1.5565 - val_root_mean_squared_error: 1.2476

In [ ]:
mse,rmse = model.evaluate(x_train,y_train)
print(rmse)

4/4 [==============================] - 0s 3ms/step - loss: 0.2145 - root_mean_squared_error: 0.4632
0.4631885886192322

In [ ]:
y_pred=model.predict(xtest)

3125/3125 [==============================] - 5s 1ms/step

In [ ]:
y_prd=sy.inverse_transform(y_pred)

In [ ]:
y_prd

array([[4740309.5],
       [2843678. ],
       [3907684.5],
       ...,
       [6206423.5],
       [7257390.5],
       [6862642. ]], dtype=float32)

In [ ]:
y_prd=pd.DataFrame(y_prd)
y_prd.to_csv('pred1.csv')

In [ ]:
y_prd

                 0
0      4740309.500
1      2843678.000
2      3907684.500
3      3467078.250
4      4920405.000
...            ...
99995  4171839.500
99996  1980839.125
99997  6206423.500
99998  7257390.500
99999  6862642.000

[100000 rows x 1 columns]

In [ ]:
y_prd.to_csv('predtest.csv')